// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjxcvwurtymwbwbqnbrh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqeGN2d3VydHltd2J3YnFuYnJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU0ODk5MzgsImV4cCI6MjA5MTA2NTkzOH0.jFZNqtDQWEDMKsu26IxuUAQoZ0KMz1joU1FHVooPEIM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});